"""initial

Revision ID: f81dbf6024ef
Revises: 
Create Date: 2026-05-27 19:11:05.422372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81dbf6024ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promoters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_name_raw', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_promoters_name')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('projects_inserted', sa.Integer(), nullable=False),
    sa.Column('projects_updated', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.CheckConstraint("source IN ('kaggle_seed', 'playwright_weekly', 'playwright_manual')", name='ck_scrape_runs_source'),
    sa.CheckConstraint("status IN ('running', 'success', 'failed')", name='ck_scrape_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filter_json', sa.JSON(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(), nullable=False),
    sa.Column('confirm_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirm_token', name='uq_subscriptions_confirm_token'),
    sa.UniqueConstraint('unsubscribe_token', name='uq_subscriptions_unsubscribe_token')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscriptions_active', ['confirmed_at', 'unsubscribed_at'], unique=False)
        batch_op.create_index('ix_subscriptions_email', ['email'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rera_reg_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('city_taluka', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('project_start_date', sa.Date(), nullable=True),
    sa.Column('project_end_date', sa.Date(), nullable=True),
    sa.Column('source_detail_url', sa.String(), nullable=True),
    sa.Column('source_first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("project_type IN ('residential', 'commercial', 'plotted', 'mixed', 'unknown')", name='ck_projects_project_type'),
    sa.CheckConstraint("status IN ('registered', 'suspended', 'completed', 'expired', 'unknown')", name='ck_projects_status'),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rera_reg_no', name='uq_projects_rera_reg_no')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_district', ['district'], unique=False)
        batch_op.create_index('ix_projects_promoter_id', ['promoter_id'], unique=False)
        batch_op.create_index('ix_projects_registration_date', ['registration_date'], unique=False)

    op.create_table('alerts_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'project_id', name='uq_alerts_sent_sub_proj')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts_sent')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_registration_date')
        batch_op.drop_index('ix_projects_promoter_id')
        batch_op.drop_index('ix_projects_district')

    op.drop_table('projects')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_email')
        batch_op.drop_index('ix_subscriptions_active')

    op.drop_table('subscriptions')
    op.drop_table('scrape_runs')
    op.drop_table('promoters')
    # ### end Alembic commands ###
